#!/usr/bin/env python3
"""Scan the codebase for os.getenv/os.environ usage and verify env vars.

Also writes a .env.example with discovered variables grouped by category.
Exits 1 if any REQUIRED variable is missing.
"""
import os
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def find_env_vars():
    pattern_getenv = re.compile(r"os\.getenv\(\s*['\"]([A-Z0-9_]+)['\"]")
    pattern_environ = re.compile(r"os\.environ\[\s*['\"]([A-Z0-9_]+)['\"]\s*\]")
    vars_found = set()
    for p in ROOT.rglob("*"):
        if p.is_file():
            if any(part.startswith(".venv") or part == "node_modules" for part in p.parts):
                continue
            if p.suffix.lower() not in (".py", ".json", ".yml", ".yaml", ".env", ".sql", ".md", ".ps1", ".txt", ".js", ".ts"):
                continue
            try:
                text = p.read_text(encoding="utf-8")
            except Exception:
                continue
            for m in pattern_getenv.findall(text):
                vars_found.add(m)
            for m in pattern_environ.findall(text):
                vars_found.add(m)
    return sorted(vars_found)


def validate(vars_list):
    results = []
    for v in vars_list:
        val = os.getenv(v)
        status = "SET" if val else "MISS"
        note = ""
        if v == "DATABASE_URL":
            note = "postgresql://" if val and val.startswith("postgresql://") else ""
        if v == "N8N_BASE_URL":
            note = "https://" if val and val.startswith("https://") else ""
        if v == "BACKEND_PUBLIC_URL":
            note = "https://" if val and val.startswith("https://") else ""
        if v in ("N8N_API_KEY", "N8N_CALLBACK_SECRET"):
            note = "OK" if val else "REQUIRED"
        results.append((v, status, note))
    return results


def print_table(rows):
    # simple fixed-width table
    name_w = max(len(r[0]) for r in rows) if rows else 10
    hdr = f"┌{'─'*(name_w+2)}┬────────┬──────────────┐"
    try:
        print(hdr)
        print(f"│ {'Variable'.ljust(name_w)} │ Status │ Note         │")
        print(f"├{'─'*(name_w+2)}┼────────┼──────────────┤")
        for name, status, note in rows:
            note = note or ""
            print(f"│ {name.ljust(name_w)} │ {'✅ SET' if status=='SET' else '❌ MISS'} │ {note.ljust(12)} │")
        print(f"└{'─'*(name_w+2)}┴────────┴──────────────┘")
    except UnicodeEncodeError:
        # Fallback to ASCII-friendly output on terminals that can't render box chars
        print("VARIABLE".ljust(name_w + 2), "STATUS", "NOTE")
        print("-" * (name_w + 2), "------", "----")
        for name, status, note in rows:
            note = note or ""
            print(name.ljust(name_w + 2), ("SET" if status == "SET" else "MISS"), note)


def write_env_example(vars_list):
    # group variables
    db = [v for v in vars_list if 'DATABASE' in v]
    n8n = [v for v in vars_list if v.startswith('N8N')]
    backend = [v for v in vars_list if 'BACKEND' in v or v.startswith('FASTAPI')]
    auth = [v for v in vars_list if any(k in v for k in ('KEY', 'SECRET', 'TOKEN', 'ADMIN')) and v not in n8n]
    other = [v for v in vars_list if v not in (db + n8n + backend + auth)]

    lines = []
    lines.append("# .env.example — generated by scripts/verify_env_vars.py")
    lines.append("")
    if db:
        lines.append("=== Database ===")
        for v in db:
            if v == 'DATABASE_URL':
                lines.append("DATABASE_URL=postgresql://postgres:password@postgres.railway.internal:5432/railway")
            else:
                lines.append(f"{v}=")
        lines.append("")
    if n8n:
        lines.append("=== n8n Integration ===")
        for v in n8n:
            if v == 'N8N_BASE_URL':
                lines.append("N8N_BASE_URL=https://n8n-production-b3aa.up.railway.app")
            elif v == 'N8N_API_KEY':
                lines.append("N8N_API_KEY=")
            elif v == 'N8N_CALLBACK_SECRET':
                lines.append("N8N_CALLBACK_SECRET=")
            else:
                lines.append(f"{v}=")
        lines.append("")
    if backend:
        lines.append("=== Backend ===")
        for v in backend:
            if v == 'BACKEND_PUBLIC_URL':
                lines.append("BACKEND_PUBLIC_URL=https://backend-production-xxxx.up.railway.app")
            else:
                lines.append(f"{v}=")
        lines.append("")
    if auth:
        lines.append("=== Auth / Keys ===")
        for v in auth:
            lines.append(f"{v}=")
        lines.append("")
    if other:
        lines.append("=== Other discovered vars ===")
        for v in other:
            lines.append(f"{v}=")
        lines.append("")

    out = ROOT.joinpath('.env.example')
    out.write_text('\n'.join(lines), encoding='utf-8')
    print('Wrote', out)


def main():
    vars_list = find_env_vars()
    if not vars_list:
        print('No env var usages found via os.getenv/os.environ')
        sys.exit(0)

    print('Discovered env vars:')
    rows = validate(vars_list)
    print_table(rows)

    # Write .env.example
    write_env_example(vars_list)

    # Check required vars
    required = ["DATABASE_URL", "N8N_BASE_URL", "N8N_API_KEY", "BACKEND_PUBLIC_URL", "N8N_CALLBACK_SECRET"]
    missing = [r for r in required if not os.getenv(r)]
    if missing:
        print('\nMissing required env vars:', ', '.join(missing))
        print('Set them in your Railway environment or a local .env file and retry.')
        sys.exit(1)

    print('\nAll required env vars present.')
    sys.exit(0)


if __name__ == '__main__':
    main()
